### ISSUE TITLE
Error `Redirect has already been forwarded to`

### ISSUE THREAD

**Issue by hendi** [mathieuprog/redirect#1]
When using multiple `redirect`s like so

```
defmodule MyAppWeb.Router do
  import Redirect

  use MyAppWeb, :router

  redirect "/foo/", "https://foo.com", :permanent
  redirect "/bar/", "https://bar.com", :permanent
end
```

I get `Redirect has already been forwarded to. A module can only be forwarded a single time.`

My `mix.exs` contains 

```
      {:phoenix, "~> 1.4.11"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.1"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:bamboo, "~> 1.3"},
      {:redirect, "~> 0.2.0"}
```

**Comment by mathieuprog** [comment]
Thank you, I fixed it. You can change the dependency to version 0.3.0.

https://github.com/mathieuprog/redirect/commit/58307974e1aabb13ffef293fd11c3b22c365e6fd

Notes to myself:

`forward/4` cannot be used multiple times with the same module, see 
https://github.com/phoenixframework/phoenix/pull/1419 and
https://github.com/graphql-elixir/plug_graphql/issues/7

I replaced `forward/4` by `match/5`. Also just by curiosity asked the difference in IRC:
> me: is there any difference between `match(:*, "/foo", Foo, :any)` and `forward("/foo", Foo)`
> josevalim: Yes
> josevalim: Forward removes “/foo” from the connection info
> josevalim: So the callee thinks it was called without /foo
> me: josevalim, why does it do that? must be some basic common-sense but I don't see right now:D
> josevalim: So part of your code wants to assume it is mounted on root
> josevalim: And not have to care about where it was actually mounted

Before I found out about the `match/5` with catch-all path (`:*`), I used the workaround shown below with `forward/4`. The idea is to wrap `forward/4` by a dynamically generated module (see GitHub links above for the idea of a wrapper):

```
defmacro redirect(path, to, type) do
  module_content =
    quote do
      use Plug.Builder
      plug(unquote(__MODULE__), to: unquote(to), type: unquote(type))
    end

  module = :"Elixir.Redirect_#{Ecto.UUID.generate()}"

  Module.create(module, module_content, Macro.Env.location(__ENV__))

  quote do
    forward(unquote(path), unquote(module), to: unquote(to), type: unquote(type))
  end
end
```

**Comment by hendi** [comment]
Great, thank you!
